# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: specedge.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'specedge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0especedge.proto\x12\x08specedge\"\xdb\x01\n\x0fValidateRequest\x12\x12\n\nclient_idx\x18\x01 \x01(\x05\x12\x0f\n\x07req_idx\x18\x02 \x01(\x05\x12\x11\n\tinput_ids\x18\x03 \x01(\x0c\x12\x14\n\x0cposition_ids\x18\x04 \x01(\x0c\x12\x19\n\x11\x63\x61\x63he_seq_indices\x18\x05 \x01(\x0c\x12\x16\n\x0eparent_indices\x18\x06 \x01(\x0c\x12\x16\n\x0e\x61ttention_mask\x18\x07 \x01(\x0c\x12\x0f\n\x07prefill\x18\x08 \x01(\x08\x12\x13\n\x06prefix\x18\t \x01(\tH\x00\x88\x01\x01\x42\t\n\x07_prefix\"6\n\x10ValidateResponse\x12\x11\n\tselection\x18\x01 \x01(\x0c\x12\x0f\n\x07prefill\x18\x02 \x01(\x05\"\r\n\x0bSyncRequest\"\x0e\n\x0cSyncResponse\"\xe8\x01\n\x13VerifyBundleRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x11\n\tbundle_id\x18\x03 \x01(\x03\x12\x18\n\x10\x62\x61se_token_index\x18\x04 \x01(\x05\x12\x13\n\x0bprompt_hash\x18\x05 \x01(\t\x12\x13\n\x0bprefix_hash\x18\x06 \x01(\t\x12\x11\n\ttoken_ids\x18\x07 \x03(\x05\x12\x19\n\x11timestamp_send_ms\x18\x08 \x01(\x03\x12\x16\n\x0e\x64raft_model_id\x18\t \x01(\t\x12\r\n\x05\x65poch\x18\n \x01(\x05\"\xe2\x01\n\x14VerifyBundleResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x11\n\tbundle_id\x18\x02 \x01(\x03\x12\x18\n\x10\x62\x61se_token_index\x18\x03 \x01(\x05\x12\x15\n\raccept_bitmap\x18\x04 \x03(\x08\x12\x14\n\x0c\x61\x63\x63\x65pted_len\x18\x05 \x01(\x05\x12\r\n\x05r_obs\x18\x06 \x01(\x02\x12\x13\n\x0bnext_credit\x18\x07 \x01(\x05\x12\x1d\n\x15server_queue_delay_ms\x18\x08 \x01(\x02\x12\x19\n\x11server_service_ms\x18\t \x01(\x02\x32\xe5\x01\n\x0fSpecEdgeService\x12\x43\n\x08Validate\x12\x19.specedge.ValidateRequest\x1a\x1a.specedge.ValidateResponse\"\x00\x12\x37\n\x04Sync\x12\x15.specedge.SyncRequest\x1a\x16.specedge.SyncResponse\"\x00\x12T\n\x11VerifyBundleAsync\x12\x1d.specedge.VerifyBundleRequest\x1a\x1e.specedge.VerifyBundleResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'specedge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALIDATEREQUEST']._serialized_start=29
  _globals['_VALIDATEREQUEST']._serialized_end=248
  _globals['_VALIDATERESPONSE']._serialized_start=250
  _globals['_VALIDATERESPONSE']._serialized_end=304
  _globals['_SYNCREQUEST']._serialized_start=306
  _globals['_SYNCREQUEST']._serialized_end=319
  _globals['_SYNCRESPONSE']._serialized_start=321
  _globals['_SYNCRESPONSE']._serialized_end=335
  _globals['_VERIFYBUNDLEREQUEST']._serialized_start=338
  _globals['_VERIFYBUNDLEREQUEST']._serialized_end=570
  _globals['_VERIFYBUNDLERESPONSE']._serialized_start=573
  _globals['_VERIFYBUNDLERESPONSE']._serialized_end=799
  _globals['_SPECEDGESERVICE']._serialized_start=802
  _globals['_SPECEDGESERVICE']._serialized_end=1031
# @@protoc_insertion_point(module_scope)
